site_name: pokemon-ace-notes
site_url: https://it-is-final.github.io/pokemon-ace-notes/
repo_name: pokemon-ace-notes
repo_url: https://github.com/it-is-final/pokemon-ace-notes/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">pokemon-ace-notes</span> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>
nav:
  - Home: index.md
  - FireRed/LeafGreen:
    - Exit codes:
      - Box 14 exit code: frlg/exit-codes/box-14-exit.md
      - Exit code bootstrap: frlg/exit-codes/exit-code-bootstrap.md
    - Complex payloads:
      - Hexwriter: frlg/complex-payloads/hex-writer.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - content.code.annotate
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-committers:
      repository: it-is-final/pokemon-ace-notes
      branch: main
